host: invenioils.web.cern.ch

ingress:
  enabled: false
  class: nginx.yaml-internal
  sslSecretName: ""

invenioils:
  secret_name: "invenio-secrets"
  csrf_enabled: True
  existing_secret: true
  search:
    index_prefix: "es"
  logging:
    sentry:
      enabled: true
      existing_secret: true
      secret_name: "sentry-secrets"
      celery: True
      environment: "prod"
  debug: False
  debug_tb_enabled: False
  debug_tb_intercept_redirects: False
  collect_storage: flask_collect.storage.file
  mail_suppress_send: True
  spa_host: "https://invenioils.web.cern.ch"
  uwsgi:
    processes: 2
    threads: 2

haproxy:
  image: haproxy:2.1
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 250m
      memory: 500Mi

nginx:
  image: "ghcr.io/inveniosoftware/demo-invenioils/demo-invenioils-frontend:latest"

worker:
  image: "ghcr.io/inveniosoftware/demo-invenioils/demo-invenioils-backend:latest"
  imagePullSecret: ""
  app: invenio_app.celery
  concurrency: 2
  log_level: INFO
  replicas: 1
  celery_pidfile: /var/run/celerybeat.pid
  celery_schedule: /var/run/celery-schedule
  celery_pool_limit: "50"

persistence:
  enabled: true
  name: "shared-volume"
  access_mode: ReadWriteMany
  size: 10G
  storage_class: "cephfs"

redis:
  enabled: true
  host: ""
  image: "redis:7"

rabbitmq:
  enabled: true
  secret_name: "mq-secrets"
  existing_secret: true
  image: "rabbitmq:3-management"

postgresql:
  enabled: false
  existing_secret: true
  secret_name: "db-secrets"

search:
  enabled: true
  existing_secret: true
  secret_name: "search-secrets"
  host: "es"
  user: "username"
  url_prefix: ""
  port: "9200"
  use_ssl: False
  verify_certs: False
  index_prefix: ""

cronjob:
  schedule: "0 0 * * *"