{{- if .Values.rabbitmq.enabled -}}
---
{{- if .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig" }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: mq
spec:
  replicas: 1
  {{- if not (.Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig") }}
  selector:
    matchLabels:
      app: mq
  {{- end }}
  template:
    metadata:
      labels:
        app: mq
    spec:
      hostname: rabbit-host # to keep queues persistent
      containers:
        - name: mq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - containerPort: 4369
            - containerPort: 5672
            - containerPort: 15672
          env:
          - name: TZ
            value: "Europe/Zurich"
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: {{  .Values.rabbitmq.secret_name }}
                key: RABBITMQ_DEFAULT_PASS
          volumeMounts:
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 500Mi

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms"
            initialDelaySeconds: 25
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - rabbitmq-diagnostics -q ping
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: rabbitmq-volume
          emptyDir: { }
{{- end }}
