{{- if .Values.redis.enabled -}}
{{- if .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig" }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: cache
spec:
  replicas: 1
  {{- if not (.Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig") }}
  selector:
    matchLabels:
      app: cache
  {{- end }}
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: {{ .Values.redis.image }}
          env:
            - name: TZ
              value: "Europe/Zurich"
          ports:
            - containerPort: 6379
              name: tcp
          volumeMounts:
            - name: redis-volume
              mountPath: /data
          resources:
            requests:
              memory: 25Mi
              cpu: 0.1
            limits:
              memory: 250Mi
              cpu: 1
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h $(hostname) ping"
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h $(hostname) ping"
            initialDelaySeconds: 15
            timeoutSeconds: 5
      volumes:
        - name: redis-volume
          emptyDir: { }
{{- end }}