---
{{- if .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig" }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: worker
spec:
  replicas: 1
  {{- if not (.Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig") }}
  selector:
    matchLabels:
      app: worker
  {{- end }}
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.worker.image }}
        command: [
            "/bin/bash",
            "-c",
            "celery -A {{ .Values.worker.app }} worker -c {{ .Values.worker.concurrency }} -l {{ .Values.worker.log_level }}"
        ]
        envFrom:
          - configMapRef:
              name: invenio-config
        env:
        - name: TZ
          value: "Europe/Zurich"
        - name: INVENIO_CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rabbitmq.secret_name }}
              key: CELERY_BROKER_URL
        - name: INVENIO_SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.secret_name }}
              key: SQLALCHEMY_DB_URI
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.search.secret_name }}
              key: ELASTICSEARCH_PASSWORD
        - name: INVENIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.invenioils.secret_name }}
              key: SECRET_KEY
        - name: INVENIO_SECURITY_LOGIN_SALT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.invenioils.secret_name }}
              key: SECURITY_LOGIN_SALT
        - name: INVENIO_CSRF_SECRET_SALT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.invenioils.secret_name }}
              key: CSRF_SECRET_SALT
        - name: INVENIO_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.invenioils.logging.sentry.secret_name }}
              key: SENTRY_DSN
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - "celery -A {{ .Values.worker.app }} inspect ping -d celery@$(hostname)"
          initialDelaySeconds: 20
          timeoutSeconds: 30
        {{- if .Values.persistence.enabled }}
        volumeMounts:
          - name: var-run-celery
            mountPath: /var/run
          - name: shared-volume
            mountPath: /shared
        {{- end }}
        resources:
          requests:
            memory: 1Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 2
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: var-run-celery
          emptyDir: {}
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}
      {{- end }}
      {{- if .Values.worker.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.worker.imagePullSecret }}
      {{- end }}

---
{{- if .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig" }}
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: worker-with-beat
spec:
  replicas: 1
  {{- if not (.Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig") }}
  selector:
    matchLabels:
      app: worker-with-beat
  {{- end }}
  template:
    metadata:
      labels:
        app: worker-with-beat
    spec:
      containers:
      - name: worker-with-beat
        image: {{ .Values.worker.image }}
        command: [
          "/bin/bash",
          "-c",
          "celery -A {{ .Values.worker.app }} worker -c {{ .Values.worker.concurrency }} --beat -l {{ .Values.worker.log_level }}  -s {{ .Values.worker.celery_schedule }} --pidfile {{ .Values.worker.celery_pidfile }}"
        ]
        {{- if .Values.persistence.enabled }}
        volumeMounts:
          - name: var-run-celery
            mountPath: /var/run
          - name: shared-volume
            mountPath: /shared
        {{- end }}
        envFrom:
        - configMapRef:
            name: invenio-config
        env:
        - name: TZ
          value: "Europe/Zurich"
        - name: INVENIO_CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rabbitmq.secret_name }}
              key: CELERY_BROKER_URL
        - name: INVENIO_SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.secret_name }}
              key: SQLALCHEMY_DB_URI
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.search.secret_name }}
              key: ELASTICSEARCH_PASSWORD
        - name: INVENIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.invenioils.secret_name }}
              key: SECRET_KEY
        - name: INVENIO_SECURITY_LOGIN_SALT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.invenioils.secret_name }}
              key: SECURITY_LOGIN_SALT
        - name: INVENIO_CSRF_SECRET_SALT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.invenioils.secret_name }}
              key: CSRF_SECRET_SALT
        - name: INVENIO_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.invenioils.logging.sentry.secret_name }}
              key: SENTRY_DSN
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - "celery -A {{ .Values.worker.app }} inspect ping -d celery@$(hostname)"
          initialDelaySeconds: 20
          timeoutSeconds: 30
        resources:
          requests:
            memory: 1Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 2
      {{ if .Values.persistence.enabled }}
      volumes:
        - name: var-run-celery
          emptyDir: {}
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}
      {{ end }}
      {{ if .Values.worker.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.worker.imagePullSecret }}
      {{ end }}
