---
{{- if not (.Values.rabbitmq.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.rabbitmq.secret_name }}
  labels:
    app: {{ .Values.rabbitmq.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.default_password | b64enc }}
  CELERY_BROKER_URL: {{ .Values.rabbitmq.celery_broker_uri | b64enc }}

---
{{- end -}}
{{- if not (.Values.postgresql.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.postgresql.secret_name }}
  labels:
    app: {{ .Values.postgresql.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  POSTGRESQL_USER: {{ .Values.postgresql.user | b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  POSTGRESQL_HOST: {{ .Values.postgresql.host | b64enc }}
  POSTGRESQL_PORT: {{ .Values.postgresql.port | b64enc }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.database | b64enc }}
  SQLALCHEMY_DB_URI: {{ .Values.postgresql.sqlalchemy_db_uri | b64enc }}

---
{{- end -}}
{{- if not (.Values.search.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.search.secret_name }}
  labels:
    app: {{ .Values.search.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  ELASTICSEARCH_PASSWORD: {{ .Values.search.password | b64enc }}

---
{{- end -}}
{{- if and (.Values.invenioils.logging.sentry.enabled) (not .Values.invenioils.logging.sentry.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.invenioils.logging.sentry.secret_name }}
  labels:
    app: {{ .Values.invenioils.logging.sentry.secret_name }}
  annotations:
    helm.sh/resource-policy: keep
data:
  SENTRY_DSN: {{ .Values.invenioils.logging.sentry.dsn | b64enc }}

---
{{- end -}}
{{- if not (.Values.invenioils.existing_secret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: invenio-secrets
  labels:
    app: invenio-secrets
  annotations:
    helm.sh/resource-policy: keep
data:
  SECRET_KEY: {{ .Values.invenioils.secret_key | b64enc }}
  CSRF_SECRET_SALT: {{ .Values.invenioils.csrf_secret | b64enc }}
  SECURITY_LOGIN_SALT: {{ .Values.invenioils.login_salt | b64enc }}
{{- end -}}
